version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my_database  # Optional: create a default database
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork
    restart: always

  backend:
    container_name: backend
    build:
      context: ./  # Ensure you are in the right directory for Dockerfile
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - "9000:9000"
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "npx prisma db push && npm run build && npm run start"  # Ensure app starts after migrations
    networks:
      - mynetwork
    restart: always

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql_data:
